<?php

/**
* Implementation of hook_menu().
*/
function numerosprimos_menu() {
  
  $items['admin/settings/rootstack/numbers'] = array(
    'title' => 'Prime Settings',
    'description' => 'Prime settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('numerosprimos_form'),
    'access arguments' => array('administer Primes'),
    'file' => 'numerosprimos.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
	
	$items['admin/settings/rootstack/numbers/generados'] = array(
    'title' => 'Primos Generados',
    'page callback' => 'create_table',
    'access arguments' => array('administer Primes'),
    'file' => 'generados_primos.pages.inc',
    
  );

	return $items;
  
}

/**
* Implements hook_permission().
*/
function numerosprimos_permission() {
  return array(
    'access numerosprimos_page content' => array(
      'title' => t('Access content for the Current posts module'),
    )
  );
}
